package com.stanzaliving.generic_po.constants;

public interface EmailPlaceHolders {

    String USER = "user";
    String SUBMIT_ACTION = "submitAction";
    String SUBMITTED_BY = "submittedBy";
    String PO_NUMBER = "poNumber";
    String PO_DEPARTMENT = "poDepartment";
    String PO_TYPE = "poType";
    String PO_LOCATION = "poLocation";
    String PO_DURATION = "poDuration";
    String COMPANY_NAME = "companyName";
    String PO_AMOUNT = "poAmount";
    String SHORT_CLOSE_AMOUNT = "shortcloseAmount";
    String REASON = "reason";
    String L1_APPROVAL_DATE = "L1ApprovalDate";// L1approvalDate
    String L1_APPROVER_NAME = "L1ApproverName";// L1approverName
    String L2_APPROVAL_DATE = "L2ApprovalDate";// L2approvalDate
    String L2_APPROVER_NAME = "L2ApproverName";// L2approverName
    String PO_LINK = "poLink";
    String SUBMITTED_ON = "submittedOn";
    String L3_APPROVER_NAME = "L3ApproverName";
    String APPROVER_NAME = "approverName";
    String SHORT_CLOSE_REASON = "shortcloseReason";
    String CANCELLATION_REASON = "cancellationReason";
    String SEND_BACK_REASON = "sendBackReason";
    String COMMENTS = "comments";
    String PO_SHORT_CLOSE_AMOUNT = "poShortcloseAmount";
    String PO_SHORT_CLOSE_REASON = "poShortCloseReason";
    String PO_CANCELLATION_REASON = "poCancellationReason";
    String VENDOR_NAME = "vendorName";
    String PO_CREATOR_NAME = "poCreatorName";
    String PO_CREATOR_EMAIL = "poCreatorEmail";
    String SCOPE_OF_WORK = "scopeOfWork";
    //    String USER ="User";
    String ITEMS = "items";
    String GRN_USER = "grnUser";
    String ITEM_CODE = "itemCode";
    String LOCATION_NAME = "locationName";
    String MICROMARKET = "micromarket";
    String CITY = "city";
    String ITEM_NAME = "itemName";
    String ITEM_BOQ_QUANTITY = "itemBOQQuantity";
    String QTY_RECEIVED = "qtyReceived";
    String QTY_RETURNED = "qtyReturned";
    String HOUSE_NAME = "houseName";
    String QTY_INSTALLED = "qtyInstalled";
    String QTY_REJECTED = "qtyRejected";
    //    String PO_LINK = "poLlink";
    String INVOICE_NUMBER = "invoiceNumber";
    String SUBMITTER_NAME = "submitterName";
    String INVOICE_TYPE = "invoiceType";
    String INVOICE_VALUE = "invoiceValue";
    String APPROVAL_LEVEL = "approvalLevel";
    String DEDUCTION_DONE = "deductionDone";
    String DEDUCTION = "deduction";
    //    String INVOICE_LINK = "invoiceLlink";
//    String APPROVER_NAME = "ApproverName";
    String INVOICE_REJECTED_REASON = "invoiceRejectReason";// invoiceRejectreason
    String INVOICE_DEDUCTION = "invoiceDeductions";
    String PAYMENT_DATE = "paymentDate";
    String AMOUNT_PAID = "AmountPaid";
    String TDS_AMOUNT = "tdsAmount";
    String DEDUCTION_AMOUNT = "deductionAmount";
    String DEDUCTION_REASONS = "deductionReasons";
    String INVOICE_LINK = "invoiceLink";
    String TO_NUMBER = "toNumber";
    String TO_DEPARTMENT = "toDepartment";
    String TO_SOURCE_LOCATION = "toSourceLocation";
    //    String PO_DESTINATION_LOCATION = "poDestinationLocation";
    String TO_LINK = "toLink";
    String TO_DESTINATION_LOCATION = "toDestinationLocation";
    String TO_DURATION = "toDuration";
    String TO_REASON = "toReason";
    String DEPARTMENT = "department";
    String PO_CREATOR = "PO_CREATOR";
    String PREVIOUS_APPROVER = "PREVIOUS_APPROVER";
    String ACTION_SUBMITTER = "actionSubmitter";

}
