package com.stanzaliving.core.far.enums;

public enum AssetActiontype {
    ASSET_MAPPED_TO_QRCODE,
    QR_CODE_REPLACED,

    ASSET_TYPE_MODIFIED,

    ASSET_VERIFIED,
    ASSET_AUDITED,

    LOCATION_CHANGED,

    TRANSERRED_OUT,
    TRANSERRED_IN,

    HOTO_DONE,

    AMC_ADDED,
    AMC_UPDATED,
    AMC_REMOVED,
    AMC_EXPIRED,

    INSURANCE_ADDED,
    INSURANCE_UPDATED,
    INSURANCE_REMOVED,
    INSURANCE_EXPIRED
}