package com.stanzaliving.core.far.enums;

public enum FARFields {

    ASSET_ASSETID(FARSections.ASSET),
    //ASSET_PONUMBER(FARSections.ASSET), - Handled in Separate api
    ASSET_POTYPE(FARSections.ASSET),
    ASSET_POURL(FARSections.ASSET),
    ASSET_TONUMBER(FARSections.ASSET),
    ASSET_GRNNUMBER(FARSections.ASSET),
    ASSET_VENDORUUID(FARSections.ASSET),
    ASSET_VENDORNAME(FARSections.ASSET),
    ASSET_PODATE(FARSections.ASSET),
    ASSET_ACQUISITIONDATE(FARSections.ASSET),
    ASSET_ACQUISITIONPRICE(FARSections.ASSET),
    ASSET_UNITRATE(FARSections.ASSET),
    ASSET_GSTPCT(FARSections.ASSET),
    ASSET_OTHERFEE(FARSections.ASSET),
    ASSET_OTHERFEETAX(FARSections.ASSET),
    ASSET_INVOICENUMBER(FARSections.ASSET),
    ASSET_INVOICEDATE(FARSections.ASSET),
    ASSET_INVOICEVENDORDOCPATH(FARSections.ASSET),
    ASSET_ASSETNAME(FARSections.ASSET),
    ASSET_ASSETDESCRIPTION(FARSections.ASSET),
    ASSET_OWNER(FARSections.ASSET),
    ASSET_LANDLORDNAME(FARSections.ASSET),
    ASSET_VERIFIEDON(FARSections.ASSET),
    ASSET_LASTAUDITEDON(FARSections.ASSET),
    ASSET_VERIFIEDBY(FARSections.ASSET),
    ASSET_LASTAUDITEDBY(FARSections.ASSET),
    ASSET_ITEMSINPACKAGE(FARSections.ASSET),
    ASSET_IMAGES(FARSections.ASSET),
    ASSET_ASSETTYPE(FARSections.ASSET),
    ASSET_RENTALSTARTDATE(FARSections.ASSET),
    ASSET_RENTALENDDATE(FARSections.ASSET),
    ASSET_QRCODE(FARSections.ASSET),
    ASSET_AMCUUID(FARSections.ASSET),
    ASSET_INSURANCEUUID(FARSections.ASSET),
    ASSET_ITEMUUID(FARSections.ASSET),
    ASSET_ALLOCATIONUUID(FARSections.ASSET),
    ASSET_ASSETSTATUS(FARSections.ASSET),
    ASSET_BRANDNAME(FARSections.ASSET),
    ASSET_MODELNAME(FARSections.ASSET),
    ASSET_SERIALNUMBER(FARSections.ASSET),
    ASSET_ASSETCONDITION(FARSections.ASSET),
    ASSET_TASKDUECOUNT(FARSections.ASSET),
    ASSET_TEXTCOLOR(FARSections.ASSET),
    ASSET_BGCOLOR(FARSections.ASSET),
    ASSET_LABEL(FARSections.ASSET),

    ALLOCATION_ADDRESSUUID(FARSections.ALLOCATION), // Call transformation_master with addressUuid - It will return microMarketUuid & cityUuid, locationName
    ALLOCATION_LOCATIONTYPE(FARSections.ALLOCATION),
    ALLOCATION_ALLOCATEDTO(FARSections.ALLOCATION),
    ALLOCATION_ALLOCATEDIN(FARSections.ALLOCATION),
    ALLOCATION_OTHERAREANAME(FARSections.ALLOCATION),
    ALLOCATION_ROOMNUMBER(FARSections.ALLOCATION),
    ALLOCATION_FLOORNUMBER(FARSections.ALLOCATION),
    ALLOCATION_EMPLOYEEID(FARSections.ALLOCATION),
    ALLOCATION_EMPLOYEEDEPARTMENT(FARSections.ALLOCATION),
    ALLOCATION_EMPLOYEENAME(FARSections.ALLOCATION),
    ALLOCATION_EMPLOYEEEMAIL(FARSections.ALLOCATION),

    ITEM_ITEMCODE(FARSections.ITEM),
    ITEM_GLCODE(FARSections.ITEM),
    ITEM_COSTHEAD(FARSections.ITEM),
    ITEM_ITEMNAME(FARSections.ITEM),
    ITEM_ITEMDESCRIPTION(FARSections.ITEM),
    ITEM_COSTHEADLABEL(FARSections.ITEM),
    ITEM_CATEGORY(FARSections.ITEM),
    ITEM_SUBCATEGORY(FARSections.ITEM),
    ITEM_CATEGORYLABEL(FARSections.ITEM),
    ITEM_SUBCATEGORYLABEL(FARSections.ITEM),
    ITEM_UOM(FARSections.ITEM), // unitOfMeasuremnet

    AMC_AMCTYPE(FARSections.AMC),
    AMC_VENDORNAME(FARSections.AMC),
    AMC_AMCSTARTDATE(FARSections.AMC),
    AMC_AMCENDDATE(FARSections.AMC),
    AMC_POCNAME(FARSections.AMC),
    AMC_POCCONTACTNUMBER(FARSections.AMC),
    AMC_POCEMAIL(FARSections.AMC),
    AMC_INCLUDES(FARSections.AMC),
    AMC_EXCLUDES(FARSections.AMC),
    AMC_AMCDOCUMENTPATH(FARSections.AMC),

    INSURANCE_INSURANCETYPE(FARSections.INSURANCE),
    INSURANCE_INSURANCECOMPANY(FARSections.INSURANCE),
    INSURANCE_CONTACTNUMBER(FARSections.INSURANCE),
    INSURANCE_STARTDATE(FARSections.INSURANCE),
    INSURANCE_ENDDATE(FARSections.INSURANCE),
    INSURANCE_INSUREDVALUE(FARSections.INSURANCE),
    INSURANCE_INSURANCEAMOUNT(FARSections.INSURANCE),
    INSURANCE_INSURANCEDOCUMENTPATH(FARSections.INSURANCE);

    private FARSections section;

    FARFields(FARSections section) {
        this.section = section;
    }

    public FARSections getSection () {
        return section;
    }
}