package com.stanzaliving.core.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum LookingFor {

    REAL_ESTATE_PARTNERSHIPS,

    OPERATIONS_AND_SERVICE_PARTNERS,

    HUMAN_RESOURCES_AND_JOB_OPENINGS,

    BRAND_AND_MEDIA_PARTNERS,

    LOOKING_FOR_STANZA_LIVING_RESIDENCES,

    PRICING_AND_PAYMENTS,

    PRE_BOOKING_AND_CANCELLATIONS,

    NOTHING_THATS_LISTED_HERE_SORRY,

    BOOKING_CANCELLATIONS,

    UNLOCK_DISCOUNT_COUPON_REFUND
}
