package com.stanzaliving.filixIntegration.Enum;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum CustomerApiEnum {

    CUSTOMER_CREATION("CUSTOMER_CREATION"),
    CUSTOMER_INVOICE("CUSTOMER_INVOICE"),
    CUSTOMER_DEPOSIT("CUSTOMER_DEPOSIT"),
    CUSTOMER_REFUND("CUSTOMER_REFUND"),
    CUSTOMER_PAYMENT("CUSTOMER_PAYMENT"),
    CUSTOMER_CREDIT_MEMO("CUSTOMER_CREDIT_MEMO"),
    CUSTOMER_SD_ADJUSTMENT("CUSTOMER_SD_ADJUSTMENT"),
    CUSTOMER_PAYMENT_REMAP("CUSTOMER_PAYMENT_REMAP"),
    CUSTOMER_CARRY_FORWARD("CUSTOMER_CARRY_FORWARD");

    String name;

}