package com.stanzaliving.core.inventory_transformations.model;

public enum RequestType {
	VAS_OPT_OUT,
	VAS_OPT_IN,
	ROOM_CHANGE_AFTER_ONBOARDING_COMPLETION,
	CONTRACT_EXTENSION,
	PAYMENT_FREQUENCY_UPDATE,
	BOOKING_CONFIRM, 
	CONTRACT_START_DATE_CHANGE,
	PENALTY_WAIVE_OFF,
	BROKER_LEAD_TRANSACTION
}
