package com.stanzaliving.core.opscalculator.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum FixedVariableCalculatorCategory {

	AUDIT,
	DG,
	ELECTRICITY,
	EQUIPMENT,
	FOOD,
	HK,
	INTERNET,
	LAUNDRY,
	OE,
	PERSONNEL,
	RC,
	REPAIR,
	BUILDING,
	SECURITY,
	SUBSCRIPTION,
	UNIFORM_COSTS,
	UTILITIES,
	UNDER_WRITTEN,
	WATER,
	ELECTRICITY_FIXED,
	WATER_FIXED,
	WATER_VARIABLE,
	REPAIR_MANPOWER,
	REPAIR_AMC,
	REPAIR_MATERIAL,
	SUBSCRIPTION_DTH,
	SUBSCRIPTION_CHEMICALS,
	SUBSCRIPTION_EQUIPMENTS,
	SUBSCRIPTION_GENERAL,
	BUILDING_PEST,
	BUILDING_TANK,
	BUILDING_FACADE,
	BUILDING_FLOOR,
	BUILDING_UPHOLESTRY,
	BUILDING_FUMIGATION,
	BUILDING_GARBAGE,
	TRANSPORT;

}
