package com.stanzaliving.core.paymentPlan.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
@AllArgsConstructor
public enum LineItemValue {

    LICENSE_FEE("LICENSE FEE"),
    CITY_HEAD_BUFFER("CITY HEAD BUFFER"),
    UPSELL("UPSELL"),
    PRICE_BUMP("PRICE BUMP"),
    PACKAGED_SERVICE_FEE("PACKAGED SERVICE FEE"),
    FOOD_SERVICE_FEE("FOOD SERVICE FEE"),
    SECURITY_DEPOSIT("SECURITY DEPOSIT"),
    ONBOARDING_CHARGE("ONBOARDING CHARGE"),
    MAINTENANCE_FEE("MAINTENANCE FEE"),
    ANNUAL_MAINTENANCE_FEE("ANNUAL MAINTENANCE FEE"),
    VAS_FEE("VAS FEE"),
    DISCOUNT("DISCOUNT"),
    PRICING_STRATEGY_AMOUNT("PRICING STRATEGY AMOUNT"),
    ACCOMMODATION_FEE("ACCOMMODATION FEE"),
    GST_WAIVE_OFF("GST WAIVE OFF"),
    BUMP_UP_PRICE("BUMP UP PRICE"),
    RENTAL_FEE("RENTAL FEE"),
    SERVICE_FEE("SERVICE FEE"),
    MANAGEMENT_FEE("MANAGEMENT FEE"),
    PROCESSING_FEE("PROCESSING FEE");

    private String name;

}