package com.stanzaliving.core.oracle.integration.enums;

public enum OracleServiceOwner {

    LOCATION,
    DEPARTMENT,
    ITEM,
    VENDOR,
    PO,
    GRN,
    TO,
    INVOICE,
    ADJUST_INVENTORY,
	CUSTOMER_CREATION,
    CUSTOMER_INVOICE,
    CUSTOMER_DEPOSIT,
    CUSTOMER_REFUND,
    CUSTOMER_PAYMENT,
    CUSTOMER_CREDIT_MEMO,
    CUSTOMER_SD_ADJUSTMENT,
	CUSTOMER_PAYMENT_REMAP,
	CUSTOMER_CARRY_FORWARD;

}
